// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkzoixqbhjydxskzykyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxrem9peHFiaGp5ZHhza3p5a3luIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzUyMDIsImV4cCI6MjA2NDQ1MTIwMn0.t1dPa_HoUUwjRxE_hfNY1EhXWlXrQsLtok9OjiIF71k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});